### ISSUE TITLE
not annotated

### ISSUE THREAD

**Issue by andrconstruction** [yzen-dev/plain-to-class#3]
0.4.2
Is there should be some additional set?
I has an error with annotations

[Semantical Error] The class "ClassTransformer\Attributes\WritingStyle" is not annotated with @Annotation.

**Comment by andrconstruction** [comment]
As proposal may advise make a class like this

`

declare(strict_types=1);

namespace ClassTransformer\Attributes;

use Doctrine\Common\Annotations\Annotation;

/**
 * @Annotation
 * @Target({"PROPERTY"})
 * @package App\Common\Annotaion
 */
final class WritingStyle extends Annotation
{
    /** Check all possible styles */
    public const STYLE_ALL = 'ALL';
    /** Check camelCase styles */
    public const STYLE_CAMEL_CASE = 'CAMEL_CASE';
    /** Check snake_case styles */
    public const STYLE_SNAKE_CASE = 'SNAKE_CASE';
}
`

**Comment by yzen-dev** [comment]
Hi! Is package installed in Symfony project? I think he's swearing.

I will try to reproduce this problem and find a solution.

**Comment by andrconstruction** [comment]
> Hi! Is package installed in Symfony project? I think he's swearing.
> 
> I will try to reproduce this problem and find a solution.

yes within symfony
