### ISSUE TITLE
What you think about a files data.

### ISSUE THREAD

**Issue by andrconstruction** [yzen-dev/plain-to-class#4]
If one of fields has a Symfony\Component\HttpFoundation\File\File instance, this case transformer try to create new Class, but an object should has parameters for a constructor. Within the transformer itself it trying to create simple class without params and throw an error, will you plan to handle this variant, or not.

**Comment by andrconstruction** [comment]
Or as i suspect for this situation should   I use transform method

**Comment by andrconstruction** [comment]
Have you any examples?

**Comment by yzen-dev** [comment]
Hi! 
At the moment, you can remove the strict type from the field:
```php
class DTO
{
    public $file;
}
```

But your remark is correct. I will publish the code changes soon, and the No transform attribute will be added there. It indicates that the value don't need to be converted, only set.

```php
class DTO
{
    #[NotTransform()]
    public File $file;
}

**Comment by yzen-dev** [comment]
Release v1.2
Add NotTransform
